version: "3"
services:

  onz-faucet:
    image: onz/faucet:testnet
    depends_on:
      - faucet-cache
    ports:
      - "127.0.0.1:6000:6000"
    networks:
      - onz-faucet
    restart: on-failure
    volumes:
      - ./config.docker.json:/home/onz/onz-faucet/config.json
    environment:
      - NODE_ENV=production

  faucet-cache:
    image: redis:alpine
    networks:
      - onz-faucet
    restart: on-failure

networks:
  onz-faucet:
